# Generated by Django 6.0.3 on 2026-03-26 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagamento_id_externo', models.CharField(max_length=255, unique=True)),
                ('status_mp', models.CharField(max_length=50)),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True)),
                ('payload_raw', models.TextField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='orders.pedido')),
            ],
        ),
    ]
